import type {
  SCIMenuFeature,
  SCIStaffRole,
  SCIStaffDesk,
  SCIInternalStaff,
} from "./staffTypes";

const now = new Date().toISOString();

export const INITIAL_MENU_FEATURES: SCIMenuFeature[] = [
  {
    featureId: "dashboard",
    label: "Dashboard",
    path: "/dashboard",
    category: "dashboard",
    description: "Main SCI Control Centre dashboard.",
    status: "active",
  },
  {
    featureId: "vendors",
    label: "Vendor Management",
    path: "/vendors",
    category: "business",
    description: "Manage vendor records and onboarding.",
    status: "active",
  },
  {
    featureId: "activation_requests",
    label: "Activation Requests",
    path: "/activations",
    category: "business",
    description: "Review vendor and application activation requests.",
    status: "active",
  },
  {
    featureId: "plans_pricing",
    label: "Plans & Pricing",
    path: "/plans",
    category: "commercial",
    description: "Manage SCI platform pricing plans.",
    status: "active",
  },
  {
    featureId: "pos_licensing",
    label: "POS Licensing",
    path: "/pos",
    category: "licensing",
    description: "Issue and manage iTredPOS licenses.",
    status: "active",
  },
  {
    featureId: "app_licensing",
    label: "App Licensing",
    path: "/apps",
    category: "licensing",
    description: "Manage application licenses.",
    status: "active",
  },
  {
    featureId: "staff_management",
    label: "Staff Management",
    path: "/staff",
    category: "internal_admin",
    description: "Create and manage internal SCI staff.",
    status: "active",
  },
  {
    featureId: "role_creator",
    label: "Staff Role Creator",
    path: "/roles",
    category: "internal_admin",
    description: "Create staff roles and assign permissions.",
    status: "active",
  },
  {
    featureId: "desk_creator",
    label: "Staff Desk Creator",
    path: "/desks",
    category: "internal_admin",
    description: "Create staff desks and assign menu access.",
    status: "active",
  },
  {
    featureId: "menu_features",
    label: "Menu Features",
    path: "/menu-features",
    category: "internal_admin",
    description: "Manage menu tree and grantable feature access.",
    status: "active",
  },
  {
    featureId: "rpn_management",
    label: "RPN Management",
    path: "/rpn",
    category: "operations",
    description: "Manage independent vendor acquisition agents.",
    status: "active",
  },
  {
    featureId: "audit_logs",
    label: "Audit Logs",
    path: "/audit",
    category: "operations",
    description: "Review system activity and admin decisions.",
    status: "active",
  },
  {
    featureId: "settings",
    label: "System Settings",
    path: "/settings",
    category: "platform",
    description: "Manage platform settings.",
    status: "active",
  },
];

export const INITIAL_STAFF_ROLES: SCIStaffRole[] = [
  {
    roleId: "role_sysadmin",
    roleName: "SysAdmin",
    description: "Full access to SCI Control Centre administration.",
    menuFeatureIds: INITIAL_MENU_FEATURES.map((feature) => feature.featureId),
    canCreateEmployee: true,
    canCreateRole: true,
    canCreateDesk: true,
    canGrantMenuAccess: true,
    status: "active",
    createdAt: now,
    updatedAt: now,
  },
  {
    roleId: "role_operations",
    roleName: "Operations Officer",
    description: "Manages vendors, activation requests, RPN and daily operations.",
    menuFeatureIds: [
      "dashboard",
      "vendors",
      "activation_requests",
      "rpn_management",
      "audit_logs",
    ],
    canCreateEmployee: false,
    canCreateRole: false,
    canCreateDesk: false,
    canGrantMenuAccess: false,
    status: "active",
    createdAt: now,
    updatedAt: now,
  },
  {
    roleId: "role_licensing",
    roleName: "Licensing Officer",
    description: "Manages pricing, POS licenses and app licenses.",
    menuFeatureIds: [
      "dashboard",
      "plans_pricing",
      "pos_licensing",
      "app_licensing",
      "audit_logs",
    ],
    canCreateEmployee: false,
    canCreateRole: false,
    canCreateDesk: false,
    canGrantMenuAccess: false,
    status: "active",
    createdAt: now,
    updatedAt: now,
  },
];

export const INITIAL_STAFF_DESKS: SCIStaffDesk[] = [
  {
    deskId: "desk_sysadmin",
    deskName: "SysAdmin Control Desk",
    deskCode: "DESK-SYSADMIN",
    description: "Full administrative command desk.",
    menuFeatureIds: INITIAL_MENU_FEATURES.map((feature) => feature.featureId),
    assignedStaffIds: ["staff_sysadmin"],
    dashboardType: "executive",
    status: "active",
    createdAt: now,
    updatedAt: now,
  },
  {
    deskId: "desk_operations",
    deskName: "Operations Desk",
    deskCode: "DESK-OPS",
    description: "Vendor onboarding and RPN operations desk.",
    menuFeatureIds: [
      "dashboard",
      "vendors",
      "activation_requests",
      "rpn_management",
      "audit_logs",
    ],
    assignedStaffIds: ["staff_operations", "staff_licensing"],
    dashboardType: "operations",
    status: "active",
    createdAt: now,
    updatedAt: now,
  },
  {
    deskId: "desk_inactive",
    deskName: "Inactive Operations Terminal",
    deskCode: "DESK-INACTIVE",
    description: "Suspended system configuration terminal.",
    menuFeatureIds: [
      "dashboard",
      "vendors"
    ],
    assignedStaffIds: ["staff_inactive"],
    dashboardType: "operations",
    status: "inactive",
    createdAt: now,
    updatedAt: now,
  },
  {
    deskId: "desk_restricted",
    deskName: "Restricted Access Terminal",
    deskCode: "DESK-RESTRICTED",
    description: "Sandbox console desk with zero features.",
    menuFeatureIds: [],
    assignedStaffIds: ["staff_restricted"],
    dashboardType: "support",
    status: "active",
    createdAt: now,
    updatedAt: now,
  }
];

export const INITIAL_INTERNAL_STAFF: SCIInternalStaff[] = [
  {
    staffId: "staff_sysadmin",
    fullName: "SCI SysAdmin",
    email: "admin@seigencommerce.com",
    phone: "",
    roleId: "role_sysadmin",
    assignedDeskIds: ["desk_sysadmin"],
    defaultDeskId: "desk_sysadmin",
    canCreateEmployee: true,
    dashboardType: "executive",
    status: "active",
    createdAt: now,
    updatedAt: now,
  },
  {
    staffId: "staff_operations",
    fullName: "Sarah Jenkins",
    email: "sarah@seigencommerce.com",
    phone: "",
    roleId: "role_operations",
    assignedDeskIds: ["desk_operations"],
    defaultDeskId: "desk_operations",
    canCreateEmployee: false,
    dashboardType: "operations",
    status: "active",
    createdAt: now,
    updatedAt: now,
  },
  {
    staffId: "staff_licensing",
    fullName: "Marcus Vance",
    email: "marcus@seigencommerce.com",
    phone: "",
    roleId: "role_licensing",
    assignedDeskIds: ["desk_operations"],
    defaultDeskId: "desk_operations",
    canCreateEmployee: false,
    dashboardType: "sales",
    status: "active",
    createdAt: now,
    updatedAt: now,
  },
  {
    staffId: "staff_inactive",
    fullName: "Blocked Operator",
    email: "blocked@seigencommerce.com",
    phone: "",
    roleId: "role_operations",
    assignedDeskIds: ["desk_operations"],
    defaultDeskId: "desk_operations",
    canCreateEmployee: false,
    dashboardType: "operations",
    status: "inactive",
    createdAt: now,
    updatedAt: now,
  },
  {
    staffId: "staff_restricted",
    fullName: "No Clearance Operator",
    email: "noclearance@seigencommerce.com",
    phone: "",
    roleId: "role_operations",
    assignedDeskIds: ["desk_restricted"],
    defaultDeskId: "desk_restricted",
    canCreateEmployee: false,
    dashboardType: "support",
    status: "active",
    createdAt: now,
    updatedAt: now,
  }
];


